[release/2.4] Add miopen_batch_norm to meta_registrations
This PR adds a meta_registration for miopen_batch_norm to resolve this issue

```
NotImplementedError: aten::miopen_batch_norm: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered.
```

cherry-picked from upstream https://github.com/pytorch/pytorch/commit/4e4182dbd0417a859919183df86f5d40cf0ce2e6

Co-authored-by: Jack Taylor <jack.taylor@amd.com>
(cherry picked from commit 0ca1e5ba8fdf9b03beec04918ef3394a6ef53936)