[release/2.6] fix scaled matmul and test_float8_basics_cuda (#2739)
This PR fixes:
- test_matmul_cuda.py::TestFP8MatmulCudaCUDA::test_float8_basics_cuda -
AssertionError: RuntimeError not raised
-
test_matmul_cuda.py::TestFP8MatmulCudaCUDA::test_scaled_mm_vs_emulated_row_wise_bfloat16_cuda
- AssertionError: Tensor-likes are not close!

need to swap A_SCALE and B_SCALE descriptors data if `use_rowwise` like
as
[HIPBLASLT_VEC_EXT](https://github.com/ROCm/pytorch/blob/78f6ff789a11bcdca072f019305485d1cf06c7eb/aten/src/ATen/cuda/CUDABlas.cpp#L1450-L1454)

Fixes SWDEV-544098