TestHFPretrained.test_pretrained BC config attr
test/dynamo/test_model_output.py TestHFPretrained.test_pretrained fails with

```
2025-12-04T07:49:10.0124562Z =================================== FAILURES ===================================
2025-12-04T07:49:10.0124736Z _______________________ TestHFPretrained.test_pretrained _______________________
2025-12-04T07:49:10.0124899Z Traceback (most recent call last):
2025-12-04T07:49:10.0125093Z   File "/var/lib/jenkins/pytorch/test/dynamo/test_model_output.py", line 45, in test_pretrained
2025-12-04T07:49:10.0125285Z     ref = fn(x, tmp)
2025-12-04T07:49:10.0125461Z   File "/var/lib/jenkins/pytorch/test/dynamo/test_model_output.py", line 40, in fn
2025-12-04T07:49:10.0125654Z     return a + torch.ones(2) * tmp.max_length
2025-12-04T07:49:10.0125902Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 198, in __getattribute__
2025-12-04T07:49:10.0126146Z     return super().__getattribute__(key)
2025-12-04T07:49:10.0126318Z AttributeError: 'PreTrainedConfig' object has no attribute 'max_length'
```

This affected both CUDA and ROCm.  I believe theroot cause is that some
ancient version of huggingface transformers is getting installed
somewhere.  A 6+ year old HF transformers the attr was named
generate_max_length instead of max_length.

https://github.com/huggingface/transformers/blame/77d397202ba3daa013c94696e9825de8e20145e8/transformers/configuration_utils.py#L65

This PR fixes the symptom, not the root cause.