[release/2.6] Define datatypes when ROCM_VERSION >= 70000 (#2471)
Fixes SWDEV-543698

Cherry-picked from https://github.com/ROCm/pytorch/pull/2468

This PR fixes the errors like below:

[rank7]: RuntimeError: /tmp/comgr-c3c81b/input/CompileSourceejOPx6:34:8:
error: unknown type name 'uint64_t'; did you mean
'__hip_internal::uint64_t'? [rank7]: 34 | if(((uint64_t) t0.data) % (4 *
sizeof(half)) != 0) flag_vec4 = false;

Earlier uint64_t was defined in HIP headers in std namespace. Now it is
moved to __hip_internal namespace in hip headers. This change is made in
ROCm 7.0.

Fixes https://ontrack-internal.amd.com/browse/SWDEV-543698